pipeline {
    agent any
    stages {
        stage('run bat program') {
            steps {
                bat "C:\\IRI\\workbench-demos\\sub\\new_subset\\new_subset.bat"
            }
        }
    }
}